import { useMemo, useState } from "react";
import { cases } from "../mocks/data";
import { Button, Input, PageHeader, RiskBadge, Select, SeverityBadge, StatusBadge } from "../components/ui/core";

export function CasesPage({ navigate }: { navigate:(path:string)=>void }) {
  const [search,setSearch]=useState(""); const [type,setType]=useState("All types"); const [status,setStatus]=useState("All statuses"); const [sort,setSort]=useState("Last updated");
  const filtered=useMemo(()=>cases.filter(c=>(c.name+c.reference).toLowerCase().includes(search.toLowerCase())&&(type==="All types"||c.type===type)&&(status==="All statuses"||c.status===status)).sort((a,b)=>sort==="Highest risk"?b.risk-a.risk:sort==="Evidence count"?b.evidenceCount-a.evidenceCount:cases.indexOf(a)-cases.indexOf(b)),[search,type,status,sort]);
  return <><PageHeader eyebrow="Case management" title="Cases" description="Find, review, and open historical, live, and hybrid IoT investigations." actions={<Button variant="primary">＋ New case</Button>}/><div className="case-status-summary" aria-label="Case status summary"><div><b>{cases.length}</b><span>Cases</span></div><div><i className="status-dot active"/><b>{cases.filter(c=>c.status==="Active"||c.status==="Monitoring").length}</b><span>Active</span></div><div><i className="status-dot review"/><b>{cases.filter(c=>c.status==="Review").length}</b><span>In review</span></div><div><i className="status-dot closed"/><b>{cases.filter(c=>c.status==="Closed").length}</b><span>Closed</span></div></div><div className="table-panel cases-register"><div className="table-toolbar"><div className="search-wrap">⌕<Input placeholder="Search cases or reference…" value={search} onChange={setSearch}/></div><Select value={type} onChange={setType} ariaLabel="Filter by case type"><option>All types</option><option>Batch</option><option>Live</option><option>Hybrid</option></Select><Select value={status} onChange={setStatus} ariaLabel="Filter by status"><option>All statuses</option><option>Active</option><option>Monitoring</option><option>Review</option><option>Closed</option></Select><span className="toolbar-spacer"/><Select value={sort} onChange={setSort} ariaLabel="Sort cases"><option>Last updated</option><option>Highest risk</option><option>Evidence count</option></Select><button className="icon-button" aria-label="Table view">☷</button></div><div className="data-table-wrap"><table className="data-table cases-table"><thead><tr><th>Case</th><th>Type</th><th>Status</th><th>Evidence</th><th>Findings</th><th>Devices</th><th>Severity</th><th>Risk</th><th>Updated</th><th/></tr></thead><tbody>{filtered.map(c=><tr key={c.id} onClick={()=>navigate(`/cases/${c.id}`)} tabIndex={0} onKeyDown={e=>e.key==="Enter"&&navigate(`/cases/${c.id}`)}><td><div className="case-cell"><span>{c.type[0]}</span><div><strong>{c.name}</strong><small>{c.reference} · {c.owner}</small></div></div></td><td><span className={`type-chip type-${c.type.toLowerCase()}`}>{c.type}</span></td><td><StatusBadge status={c.status}/></td><td>{c.evidenceCount.toLocaleString()}</td><td>{c.findingsCount}</td><td>{c.deviceCount}</td><td><SeverityBadge severity={c.severity}/></td><td><RiskBadge score={c.risk}/></td><td>{c.updated}</td><td>›</td></tr>)}</tbody></table>{filtered.length===0&&<div className="state-box"><span>◇</span><strong>No matching cases</strong><p>Adjust the search or investigation filters.</p></div>}</div><div className="table-footer"><span>Showing {filtered.length} of {cases.length} investigations</span><div><button disabled>‹</button><button className="active">1</button><button disabled>›</button></div></div></div></>;
}
