import { useEffect, useRef, useState } from "react";
import { normalizeApiError } from "../api/client";
import { phase3Api, type AssistantMessage, type AssistantSession, type ResolvedVisualization, type VisualizationLayout } from "../api/phase3";
import { Button, PageHeader, StatusBadge } from "../components/ui/core";
import { ConnectedVisualizationRenderer } from "../visualizations/ConnectedVisualizationRenderer";

function referencePath(reference: string) { const parts = reference.split(":"); if (parts[0] !== "case" || !/^\d+$/.test(parts[1] ?? "")) return "/cases"; const section = ({ finding: "findings", alert: "alerts", incident: "incidents", timeline: "timeline", evidence: "evidence", event: "events" } as Record<string, string>)[parts[2]] ?? "overview"; return `/cases/${parts[1]}/${section}${parts[3] ? `#${encodeURIComponent(parts.slice(3).join(":"))}` : ""}`; }

export function ConnectedAssistantPage({ search = window.location.search }: { search?: string }) {
  const params = new URLSearchParams(search); const selectedCase = Number(params.get("case")) || null;
  const selectedReferences = selectedCase ? ["alert", "finding", "evidence", "event", "incident", "timeline"].flatMap(kind => params.get(kind) ? [`case:${selectedCase}:${kind}:${params.get(kind)}`] : []) : [];
  const referenceKey = selectedReferences.join("|");
  const [sessionId, setSessionId] = useState<string | null>(null); const [sessions, setSessions] = useState<AssistantSession[]>([]); const [messages, setMessages] = useState<AssistantMessage[]>([]); const [fallback, setFallback] = useState<ResolvedVisualization | null>(null); const [value, setValue] = useState(""); const [state, setState] = useState<"connecting" | "ready" | "thinking" | "offline" | "failed">("connecting"); const [error, setError] = useState<string | null>(null); const operation = useRef<AbortController | null>(null);
  useEffect(() => {
    const controller = new AbortController(); const caseIds = selectedCase ? [selectedCase] : []; const storageKey = `traceveil-assistant-${selectedCase ?? "auto"}`;
    const activate = async (session: AssistantSession) => { setSessionId(session.session_id); window.localStorage.setItem(storageKey, session.session_id); const history = await phase3Api.messages(session.session_id, controller.signal); setMessages(Array.isArray(history?.items) ? history.items : []); setState("ready"); };
    void phase3Api.assistantSessions(selectedCase, controller.signal).then(async result => {
      const available = Array.isArray(result?.items) ? result.items : []; setSessions(available);
      const requested = params.get("session") ?? window.localStorage.getItem(storageKey);
      const matching = available.find(item => item.session_id === requested && (!referenceKey || item.reference_ids.join("|") === referenceKey));
      if (matching) await activate(matching); else { const created = await phase3Api.createAssistantSession(caseIds, selectedReferences, controller.signal); setSessions(items => [created, ...items]); await activate(created); }
    }).catch(reason => { if (!controller.signal.aborted) { setState("failed"); setError(normalizeApiError(reason).message); } });
    return () => controller.abort();
  }, [selectedCase, referenceKey]);
  useEffect(() => () => operation.current?.abort(), []);
  useEffect(() => { if (!selectedCase) { setFallback(null); return; } const controller = new AbortController(); void phase3Api.fallbackVisualization(selectedCase, undefined, controller.signal).then(result => setFallback(result?.layout && result?.datasets ? result : null)).catch(() => setFallback(null)); return () => controller.abort(); }, [selectedCase]);
  const refresh = async (id: string, signal?: AbortSignal) => { const result = await phase3Api.messages(id, signal); setMessages(Array.isArray(result?.items) ? result.items : []); };
  const activateSession = async (id: string) => { operation.current?.abort(); setSessionId(id); setState("connecting"); setError(null); try { await refresh(id); window.localStorage.setItem(`traceveil-assistant-${selectedCase ?? "auto"}`, id); setState("ready"); } catch (reason) { setState("failed"); setError(normalizeApiError(reason).message); } };
  const newSession = async () => { operation.current?.abort(); setState("connecting"); setError(null); try { const created = await phase3Api.createAssistantSession(selectedCase ? [selectedCase] : [], selectedReferences); setSessions(items => [created, ...items]); setMessages([]); setSessionId(created.session_id); window.localStorage.setItem(`traceveil-assistant-${selectedCase ?? "auto"}`, created.session_id); setState("ready"); } catch (reason) { setState("failed"); setError(normalizeApiError(reason).message); } };
  const ask = async (question: string) => {
    if (!sessionId || !question.trim() || state === "thinking") return;
    const controller = new AbortController(); operation.current = controller; setState("thinking"); setError(null); setValue("");
    try {
      const job = await phase3Api.ask(sessionId, question.trim(), controller.signal); await refresh(sessionId, controller.signal);
      const deadline = Date.now() + 60_000;
      for (;;) {
        await new Promise(resolve => window.setTimeout(resolve, 500)); const current = await phase3Api.assistantJob(job.job_id, controller.signal);
        if (current.status === "completed") { await refresh(sessionId, controller.signal); setState("ready"); break; }
        if (current.status === "failed") { setState(current.error?.code === "ollama_offline" ? "offline" : "failed"); setError(current.error?.message ?? "Assistant processing failed."); break; }
        if (Date.now() >= deadline) throw new Error("Assistant processing timed out. You can safely retry.");
      }
    } catch (reason) { if (!controller.signal.aborted) { setState("failed"); setError(normalizeApiError(reason).message); } }
  };
  const latestLayout = messages.reduce<VisualizationLayout | null>((layout, message) => message.visualization ?? layout, null);
  return <><PageHeader eyebrow="Grounded local assistance · Connected API" title="Traceveil Assistant" description="Narration is generated from bounded persisted context; deterministic findings remain authoritative." actions={<StatusBadge status={state}/>} />
    <div className="case-assistant-workspace global-assistant-workspace"><section className="assistant-column global-assistant-column"><header className="assistant-header"><div className="assistant-orb"><i/></div><div><span className="eyebrow">Evidence-grounded Qwen</span><h2>Investigation chat</h2><p>{selectedCase ? `Scoped to persisted case ${selectedCase}` : "Auto retrieval across persisted cases"}</p></div><span className="ai-status"><i/> {state}</span></header>
      <div className="assistant-scope-panel"><div><span className="field-label">Conversation history</span><b>{selectedReferences.length ? `${selectedReferences.length} selected reference${selectedReferences.length === 1 ? "" : "s"}` : selectedCase ? `Case ${selectedCase}` : "Automatic cross-case retrieval"}</b></div><select aria-label="Conversation history" value={sessionId ?? ""} onChange={event => void activateSession(event.target.value)}><option value="" disabled>Select conversation</option>{sessions.map(session => <option value={session.session_id} key={session.session_id}>{session.title} · {session.message_count}</option>)}</select><Button variant="secondary" onClick={() => void newSession()}>＋ New chat</Button></div>
      {selectedReferences.length > 0 && <div className="selected-context"><div><span className="field-label">Selected persisted context</span><b>Retrieval locked to these records</b></div><div>{selectedReferences.map(reference => <button key={reference} onClick={() => { window.location.href = referencePath(reference); }}><small>{reference.split(":")[2]}</small>{reference.split(":").slice(3).join(":")}<span>↗</span></button>)}</div></div>}
      {error && <div className="state-box" role="alert"><strong>{state === "offline" ? "Ollama is optional and offline" : "Assistant unavailable"}</strong><p>{error}</p></div>}
      <div className="assistant-thread" aria-live="polite">{messages.length ? messages.map(message => <article className={`assistant-message assistant-message-${message.role}`} key={message.message_id}><div className="message-avatar">{message.role === "assistant" ? "TV" : "IN"}</div><div className="message-content"><div className="message-byline"><b>{message.role === "assistant" ? "Traceveil Assistant" : "Investigator"}</b>{message.role === "assistant" && <span className="message-kind kind-narration">AI narration · {message.model}</span>}</div><p>{message.text}</p>{message.citations.length > 0 && <div className="assistant-references" aria-label="Verified persisted facts"><strong>Verified persisted sources</strong>{message.citations.map(reference => <a className="evidence-reference" href={referencePath(reference)} key={reference}>{reference}<span>↗</span></a>)}</div>}{message.caveats.map(caveat => <small key={caveat}>{caveat}</small>)}</div></article>) : <div className="state-box"><strong>Ask about persisted evidence</strong><p>Answers must cite records retrieved from the backend.</p></div>}{state === "thinking" && <div className="assistant-message"><div className="message-content"><p>Retrieving and validating grounded context…</p></div></div>}</div>
      <div className="suggested-prompts"><span className="field-label">Try asking</span><div>{["Summarize the highest-risk finding", "Explain the latest live alert", "Show the forensic timeline"].map(question => <button key={question} onClick={() => void ask(question)}>{question}<span>↗</span></button>)}</div></div>
      <div className="assistant-composer"><textarea value={value} onChange={event => setValue(event.target.value)} placeholder="Ask about persisted investigation evidence…" aria-label="Assistant message" onKeyDown={event => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); void ask(value); } }}/>{state === "thinking" ? <Button variant="secondary" onClick={() => { operation.current?.abort(); setState("ready"); }}>Cancel</Button> : <Button variant="primary" disabled={!sessionId} onClick={() => void ask(value)}>Ask ↑</Button>}<small><span>◇</span> Verify AI narration against cited persisted sources. Deterministic fallback remains available offline.</small></div></section>
      <section className="investigation-canvas"><header className="canvas-header"><div><span className="eyebrow">Safe visualization boundary</span><h2>{latestLayout?.title ?? fallback?.layout?.title ?? "Validated investigation overview"}</h2><p>Only allow-listed layouts and backend-resolved values are rendered.</p></div><div className="canvas-meta"><span><b>{latestLayout?.components.length ?? fallback?.layout?.components.length ?? 0}</b> validated components</span><span className="verified-data"><i/> Persisted deterministic data</span></div></header><div className="canvas-scroll">{latestLayout || fallback?.layout ? <ConnectedVisualizationRenderer layout={latestLayout} initial={latestLayout ? null : fallback}/> : <div className="state-box"><strong>Select a case to visualize</strong><p>A deterministic overview appears without requiring Qwen.</p></div>}</div></section></div></>;
}
