import { useEffect, useRef, useState } from "react";
import { normalizeApiError } from "../api/client";
import { phase3Api, type AssistantMessage } from "../api/phase3";
import { Button, PageHeader, StatusBadge } from "../components/ui/core";

const allowedVisualizations: Record<string, string> = { timeline: "Backend-ordered timeline", risk_breakdown: "Backend risk factors", event_activity: "Persisted event activity", entity_graph: "Persisted entity graph", evidence_table: "Evidence register", alert_list: "Alert register" };
function referencePath(reference: string) { const parts = reference.split(":"); if (parts[0] !== "case" || !/^\d+$/.test(parts[1] ?? "")) return "/cases"; const section = ({ finding: "findings", alert: "alerts", incident: "incidents", timeline: "timeline", evidence: "evidence", event: "events" } as Record<string, string>)[parts[2]] ?? "overview"; return `/cases/${parts[1]}/${section}${parts[3] ? `#${encodeURIComponent(parts.slice(3).join(":"))}` : ""}`; }

export function ConnectedAssistantPage({ search = window.location.search }: { search?: string }) {
  const params = new URLSearchParams(search); const selectedCase = Number(params.get("case")) || null;
  const [sessionId, setSessionId] = useState<string | null>(null); const [messages, setMessages] = useState<AssistantMessage[]>([]); const [value, setValue] = useState(""); const [state, setState] = useState<"connecting" | "ready" | "thinking" | "offline" | "failed">("connecting"); const [error, setError] = useState<string | null>(null); const operation = useRef<AbortController | null>(null);
  useEffect(() => { const controller = new AbortController(); void phase3Api.createAssistantSession(selectedCase ? [selectedCase] : [], controller.signal).then(session => { setSessionId(session.session_id); setState("ready"); }).catch(reason => { setState("failed"); setError(normalizeApiError(reason).message); }); return () => controller.abort(); }, [selectedCase]);
  useEffect(() => () => operation.current?.abort(), []);
  const refresh = async (id: string, signal?: AbortSignal) => { const result = await phase3Api.messages(id, signal); setMessages(result.items); };
  const ask = async (question: string) => {
    if (!sessionId || !question.trim() || state === "thinking") return;
    const controller = new AbortController(); operation.current = controller; setState("thinking"); setError(null); setValue("");
    try {
      const job = await phase3Api.ask(sessionId, question.trim(), controller.signal); await refresh(sessionId, controller.signal);
      for (;;) {
        await new Promise(resolve => window.setTimeout(resolve, 500)); const current = await phase3Api.assistantJob(job.job_id, controller.signal);
        if (current.status === "completed") { await refresh(sessionId, controller.signal); setState("ready"); break; }
        if (current.status === "failed") { setState(current.error?.code === "ollama_offline" ? "offline" : "failed"); setError(current.error?.message ?? "Assistant processing failed."); break; }
      }
    } catch (reason) { if (!controller.signal.aborted) { setState("failed"); setError(normalizeApiError(reason).message); } }
  };
  return <><PageHeader eyebrow="Grounded local assistance · Connected API" title="Traceveil Assistant" description="Narration is generated from bounded persisted context; deterministic findings remain authoritative." actions={<StatusBadge status={state}/>} />
    <div className="case-assistant-workspace global-assistant-workspace"><section className="assistant-column global-assistant-column"><header className="assistant-header"><div className="assistant-orb"><i/></div><div><span className="eyebrow">Evidence-grounded Qwen</span><h2>Investigation chat</h2><p>{selectedCase ? `Scoped to persisted case ${selectedCase}` : "Auto retrieval across persisted cases"}</p></div><span className="ai-status"><i/> {state}</span></header>
      {error && <div className="state-box" role="alert"><strong>{state === "offline" ? "Ollama is optional and offline" : "Assistant unavailable"}</strong><p>{error}</p></div>}
      <div className="assistant-thread" aria-live="polite">{messages.length ? messages.map(message => <article className={`assistant-message assistant-message-${message.role}`} key={message.message_id}><div className="message-avatar">{message.role === "assistant" ? "TV" : "IN"}</div><div className="message-content"><div className="message-byline"><b>{message.role === "assistant" ? "Traceveil Assistant" : "Investigator"}</b>{message.role === "assistant" && <span className="message-kind kind-narration">AI narration · {message.model}</span>}</div><p>{message.text}</p>{message.citations.length > 0 && <div className="assistant-references" aria-label="Verified persisted facts"><strong>Verified persisted sources</strong>{message.citations.map(reference => <a className="evidence-reference" href={referencePath(reference)} key={reference}>{reference}<span>↗</span></a>)}</div>}{message.visualization && <GroundedVisualization component={message.visualization.component} dataRef={message.visualization.data_ref}/>} {message.caveats.map(caveat => <small key={caveat}>{caveat}</small>)}</div></article>) : <div className="state-box"><strong>Ask about persisted evidence</strong><p>Answers must cite records retrieved from the backend.</p></div>}{state === "thinking" && <div className="assistant-message"><div className="message-content"><p>Retrieving and validating grounded context…</p></div></div>}</div>
      <div className="suggested-prompts"><span className="field-label">Try asking</span><div>{["Summarize the highest-risk finding", "Explain the latest live alert", "Show the forensic timeline"].map(question => <button key={question} onClick={() => void ask(question)}>{question}<span>↗</span></button>)}</div></div>
      <div className="assistant-composer"><textarea value={value} onChange={event => setValue(event.target.value)} placeholder="Ask about persisted investigation evidence…" aria-label="Assistant message" onKeyDown={event => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); void ask(value); } }}/><Button variant="primary" disabled={!sessionId || state === "thinking"} onClick={() => void ask(value)}>Ask ↑</Button><small><span>◇</span> Verify AI narration against cited persisted sources.</small></div></section>
      <section className="investigation-canvas"><header className="canvas-header"><div><span className="eyebrow">Safe visualization boundary</span><h2>Validated data references</h2><p>Only allow-listed layouts and backend references are accepted.</p></div></header><div className="state-box"><strong>{messages.flatMap(message => message.citations).length} cited references</strong><p>Generated code, arbitrary URLs, embedded data arrays, and unsupported components are rejected server-side.</p></div></section></div></>;
}

function GroundedVisualization({ component, dataRef }: { component: string; dataRef: string }) { const label = allowedVisualizations[component]; if (!label) return <div className="visualization-fallback" role="status"><strong>Visualization rejected</strong><p>The requested component is not allow-listed.</p></div>; return <section className="visual-panel"><header><div><span>Verified data view</span><h3>{label}</h3></div><code>v1 · {component}</code></header><div className="visual-panel-body"><p>This layout references persisted backend data; no values are embedded or calculated by the assistant.</p><a className="evidence-reference" href={referencePath(dataRef)}>Open {dataRef}<span>↗</span></a></div></section>; }
