import { useEffect, useState } from "react";
import { phase3Api, type EmailDraft, type ReportRecord } from "../api/phase3";
import { normalizeApiError } from "../api/client";
import { Button, Input, StatusBadge } from "../components/ui/core";

export function ConnectedReportsPanel({ caseId }: { caseId: number }) {
  const [reports, setReports] = useState<ReportRecord[]>([]); const [selected, setSelected] = useState<ReportRecord | null>(null);
  const [title, setTitle] = useState("Investigation report"); const [approver, setApprover] = useState("Local investigator"); const [recipient, setRecipient] = useState("");
  const [draft, setDraft] = useState<EmailDraft | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const refresh = async () => { const result = await phase3Api.reports(caseId); const items = Array.isArray(result.items) ? result.items : []; setReports(items); setSelected(current => items.find(item => item.report_id === current?.report_id) ?? items[0] ?? null); };
  useEffect(() => { const controller = new AbortController(); void phase3Api.reports(caseId, controller.signal).then(result => { const items = Array.isArray(result.items) ? result.items : []; setReports(items); setSelected(items[0] ?? null); }).catch(reason => { if (!controller.signal.aborted) setError(normalizeApiError(reason).message); }); return () => controller.abort(); }, [caseId]);
  const run = async (operation: () => Promise<unknown>) => { setBusy(true); setError(null); try { await operation(); await refresh(); } catch (reason) { setError(normalizeApiError(reason).message); } finally { setBusy(false); } };
  const download = async () => { if (!selected) return; setBusy(true); setError(null); try { const blob = await phase3Api.downloadReport(selected.report_id); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `${selected.title.replace(/[^a-z0-9]+/gi, "-").toLowerCase() || "report"}.pdf`; link.click(); URL.revokeObjectURL(url); } catch (reason) { setError(normalizeApiError(reason).message); } finally { setBusy(false); } };
  const createDraft = async () => { if (!selected || !recipient) return; setBusy(true); setError(null); try { setDraft(await phase3Api.createEmailDraft(selected.report_id, recipient, selected.title, `Attached is the approved ${selected.title}.`)); } catch (reason) { setError(normalizeApiError(reason).message); } finally { setBusy(false); } };
  return <section className="table-panel" aria-labelledby="reports-title"><div className="panel-head"><div><span className="eyebrow">Controlled delivery</span><h2 id="reports-title">Reports and email</h2></div></div><p>PDF generation is deterministic. Export and delivery require explicit approval; email is never sent automatically.</p>
    {error && <div className="state-box" role="alert"><strong>Report action failed</strong><p>{error}</p></div>}
    <div className="filter-row"><Input ariaLabel="Report title" value={title} onChange={setTitle}/><Button variant="primary" disabled={busy || !title.trim()} onClick={() => run(() => phase3Api.createReport(caseId, title.trim()))}>Create report</Button></div>
    {reports.length ? <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Report</th><th>Status</th><th>Hash</th></tr></thead><tbody>{reports.map(report => <tr key={report.report_id}><td><button className="link-button" onClick={() => { setSelected(report); setDraft(null); }}>{report.title}</button></td><td><StatusBadge status={report.status}/></td><td><code>{report.content_hash?.slice(0, 16) ?? "Not generated"}</code></td></tr>)}</tbody></table></div> : <div className="state-box"><strong>No reports</strong><p>Create a draft after reviewing the persisted investigation.</p></div>}
    {selected && <div className="panel report-controls"><h3>{selected.title}</h3><p>Report ID <code>{selected.report_id}</code></p><div className="filter-row"><Button disabled={busy} onClick={() => run(() => phase3Api.generateReport(selected.report_id))}>Generate PDF</Button><Input ariaLabel="Report approver" value={approver} onChange={setApprover}/><Button variant="primary" disabled={busy || selected.status !== "generated" || !approver.trim()} onClick={() => run(() => phase3Api.approveReport(selected.report_id, approver.trim()))}>Approve report</Button><Button disabled={busy || selected.status !== "approved"} onClick={download}>Download approved PDF</Button></div>
      {selected.status === "approved" && <div className="report-email"><h3>Approval-gated email</h3><div className="filter-row"><Input ariaLabel="Recipient email" placeholder="recipient@example.test" value={recipient} onChange={setRecipient}/><Button disabled={busy || !recipient} onClick={createDraft}>Create email draft</Button></div>{draft && <div className="state-box"><strong>Email draft: {draft.status}</strong><p>{draft.recipient} · {draft.subject}</p><div className="filter-row"><Button disabled={busy || draft.status !== "draft"} onClick={async () => { setBusy(true); try { setDraft(await phase3Api.approveEmail(draft.draft_id, approver)); } catch (reason) { setError(normalizeApiError(reason).message); } finally { setBusy(false); } }}>Approve email</Button><Button variant="danger" disabled={busy || draft.status !== "approved"} onClick={async () => { setBusy(true); try { setDraft(await phase3Api.sendEmail(draft.draft_id)); } catch (reason) { setError(normalizeApiError(reason).message); } finally { setBusy(false); } }}>Confirm and send</Button></div>{draft.delivery_error && <p role="alert">{draft.delivery_error}</p>}</div>}</div>}</div>}
  </section>;
}
