import { useEffect, useState } from "react";
import { getSystemStatus, type ServiceStatus } from "../api/health";
import { Button, PageHeader, Panel, StatusBadge } from "../components/ui/core";
function readService(services:ServiceStatus[],name:string){return services.find(s=>s.service===name)}
export function SystemStatusPage() {
 const [services,setServices]=useState<ServiceStatus[]>([]); const [checked,setChecked]=useState("Checking…");
 useEffect(()=>{getSystemStatus().then(v=>{setServices(v);setChecked("Just now")}).catch(()=>setChecked("Unavailable"))},[]);
 const api=readService(services,"api"),db=readService(services,"database"),ai=readService(services,"ollama");
 const cards=[{name:"Backend API",status:api?.status==="ok"?"Operational":"Unavailable",desc:"Versioned batch, live, assistant, report, and audit APIs",meta:"/api/v1 · local FastAPI"},{name:"Evidence database",status:db?.status==="ok"?"Operational":"Unavailable",desc:"Durable cases, evidence, live receipts, analyses, and audit history",meta:"SQLite · serialized transactions"},{name:"AI / Ollama",status:ai?.available?"Operational":"Optional offline",desc:"Grounded assistance is available only when the configured local model is ready",meta:ai?.model_installed?"Configured model ready":"Core investigation remains available"},{name:"Live collector",status:api?.status==="ok"?"Operational":"Unavailable",desc:"Token-authenticated HTTP ingestion with durable receipts and SSE replay",meta:"HTTP POST + SSE"}];
 return <><PageHeader eyebrow="Platform observability" title="System status" description="Runtime health and explicit capability boundaries for the connected local platform." actions={<Button onClick={()=>window.location.reload()}>↻ Refresh status</Button>}/><div className="system-banner"><div><span className="large-status-dot"/><div><h2>Connected investigation platform</h2><p>Batch and live evidence converge into persisted canonical events. Ollama and SMTP are optional environment-controlled services.</p></div></div><span>Last checked · {checked}</span></div><div className="status-card-grid">{cards.map((c,i)=><article className="service-card" key={c.name}><div><span className={`service-icon service-${i}`}>{["API","DB","AI","SSE"][i]}</span><StatusBadge status={c.status}/></div><h2>{c.name}</h2><p>{c.desc}</p><footer><i/><span>{c.meta}</span></footer></article>)}</div><div className="status-layout"><Panel title="Capability boundary"><div className="capability-table"><div><b>Capability</b><b>Current state</b><b>Notes</b></div>{[["Connected investigation views","Implemented","Backend-authored records, filters, pagination, and details"],["Batch evidence ingestion","Implemented","Validation, explicit partial approval, persistence, and reanalysis"],["Live HTTP collection","Implemented","Environment source tokens, receipts, deduplication, and device state"],["SSE delivery","Implemented","Replayable one-way stream with bounded browser buffers"],["Grounded assistant","Optional","Persisted retrieval and verified citations; retryable when Ollama is offline"],["PDF and SMTP delivery","Approval gated","Immutable approvals; SMTP send is always a separate confirmation"],["Physical hardware and MQTT","Future adapter","Simulator is the Phase 3 acceptance path"]].map(r=><div key={r[0]}><span>{r[0]}</span><StatusBadge status={r[1]}/><span>{r[2]}</span></div>)}</div></Panel><Panel title="Environment notes"><div className="notes-list"><div><i>i</i><p><b>Secrets stay server-side</b>Source tokens, Ollama configuration, and SMTP credentials are never returned by APIs.</p></div><div><i>✓</i><p><b>Deterministic authority</b>Risk, findings, ordering, and report evidence remain backend-authored.</p></div><div><i>⌁</i><p><b>Controlled delivery</b>No report email is sent without unchanged report and email approvals.</p></div></div></Panel></div></>;
}
