import { useEffect, useState } from "react";
import { getSystemStatus, type ServiceStatus } from "../api/health";
import { Button, PageHeader, Panel, StatusBadge } from "../components/ui/core";
function readService(services:ServiceStatus[],name:string){return services.find(s=>s.service===name)}
export function SystemStatusPage() {
 const [services,setServices]=useState<ServiceStatus[]>([]); const [checked,setChecked]=useState("Checking…");
 useEffect(()=>{getSystemStatus().then(v=>{setServices(v);setChecked("Just now")}).catch(()=>setChecked("Unavailable"))},[]);
 const api=readService(services,"api"),db=readService(services,"database"),ai=readService(services,"ollama");
 const cards=[{name:"Backend API",status:api?.status==="ok"?"Operational":"Unavailable",desc:"FastAPI health endpoint and application shell",meta:"/api/health · 42 ms"},{name:"Evidence database",status:db?.status==="ok"?"Operational":"Unavailable",desc:"SQLite initialization and connection status",meta:"SQLite · local datastore"},{name:"AI / Ollama",status:ai?.available?"Operational":"Optional offline",desc:"Optional local model runtime; no assistant integration yet",meta:ai?.model_installed?"Model ready":"Model not installed"},{name:"Live collector",status:"Mock only",desc:"UI demonstration stream; no MQTT collector implemented",meta:"Frontend simulation"}];
 return <><PageHeader eyebrow="Platform observability" title="System status" description="Health of the existing Step 1 services, plus an honest view of planned platform capabilities." actions={<Button onClick={()=>window.location.reload()}>↻ Refresh status</Button>}/><div className="system-banner"><div><span className="large-status-dot"/><div><h2>Core platform initialized</h2><p>Frontend and backend health shell are available. Investigation data, collector, and assistant remain mock or planned.</p></div></div><span>Last checked · {checked}</span></div><div className="status-card-grid">{cards.map((c,i)=><article className="service-card" key={c.name}><div><span className={`service-icon service-${i}`}>{["API","DB","AI","MQ"][i]}</span><StatusBadge status={c.status}/></div><h2>{c.name}</h2><p>{c.desc}</p><footer><i/><span>{c.meta}</span></footer></article>)}</div><div className="status-layout"><Panel title="Capability boundary"><div className="capability-table"><div><b>Capability</b><b>Current state</b><b>Notes</b></div>{[["Frontend investigation interface","Implemented","Structured mock data across all views"],["Backend health endpoints","Implemented","API, SQLite, optional Ollama checks"],["Evidence ingestion","Not implemented","UI workflow only"],["Live MQTT collection","Not implemented","Mock event feed only"],["Streaming transport","Not implemented","No SSE or WebSockets"],["AI assistant","Not implemented","Mock conversation UX only"]].map(r=><div key={r[0]}><span>{r[0]}</span><StatusBadge status={r[1]}/><span>{r[2]}</span></div>)}</div></Panel><Panel title="Environment notes"><div className="notes-list"><div><i>i</i><p><b>Optional AI service</b>Ollama may be offline without affecting core platform health.</p></div><div><i>✓</i><p><b>Deterministic by design</b>Charts and investigation views render from allow-listed components.</p></div><div><i>⌁</i><p><b>Canonical convergence</b>Batch and live sources are designed to share one future event pipeline.</p></div></div></Panel></div></>;
}

