import { useState } from "react";
import { assistantMessages } from "../../mocks/data";
import { Button } from "../../components/ui/core";

export function AssistantPanel() {
  const [messages, setMessages] = useState(assistantMessages);
  const [value, setValue] = useState("");
  const send = () => { if (!value.trim()) return; setMessages([...messages, { role: "user", text: value }, { role: "assistant", text: "This is a mock assistant response. Live model integration is intentionally not enabled in this frontend milestone." }]); setValue(""); };
  return <div className="assistant-shell"><aside className="context-rail"><span className="eyebrow">Evidence context</span><h3>Grounded references</h3><p>Only selected mock records are included in this conversation.</p>{["FND-1042","EVD-2026-8F21","ALT-8831","Camera · Entryway"].map(item=><button key={item}>{item}<span>×</span></button>)}<div className="context-note"><b>Mock experience</b><p>No prompt is sent to Ollama or any external model.</p></div></aside><section className="chat-panel"><div className="chat-head"><div><span className="online-dot"/><div><strong>Traceveil Assistant</strong><span>Case-grounded analysis · Mock UX</span></div></div><button>···</button></div><div className="chat-messages">{messages.map((m,i)=><div className={`message message-${m.role}`} key={i}><span>{m.role === "assistant" ? "TV" : "IN"}</span><div><small>{m.role === "assistant" ? "Traceveil Assistant" : "Investigator"}</small><p>{m.text}</p>{m.role === "assistant" && i > 0 && <div className="message-refs"><code>FND-1042</code><code>EVD-2026-8F21</code></div>}</div></div>)}</div><div className="quick-actions">{["Explain this finding","Summarize this case","Explain this alert","Draft email"].map(a=><button key={a} onClick={()=>setValue(a)}>{a}</button>)}</div><div className="composer"><textarea value={value} onChange={e=>setValue(e.target.value)} placeholder="Ask about this case’s selected evidence…" onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send();}}}/><Button variant="primary" onClick={send}>Send ↑</Button><small>Mock assistant · Verify all outputs against preserved evidence.</small></div></section></div>;
}
